### ISSUE TITLE
broken link github.com/ebfe/go.pcsclite/scard from README.md

### ISSUE THREAD

**Issue by LudovicRousseau** [ebfe/go.pcsclite#4]
https://gopkgdoc.appspot.com/pkg/github.com/ebfe/go.pcsclite/scard returns an error 404:

```
Error: Not Found
The requested URL /pkg/github.com/ebfe/go.pcsclite/scard was not found on this server.
```

**Comment by ebfe** [comment]
Recommended version to use is http://github.com/ebfe/scard though that's probably even less documented.

**Comment by LudovicRousseau** [comment]
What is the relation between https://github.com/ebfe/go.pcsclite and https://github.com/ebfe/scard?

https://github.com/ebfe/scard replaces https://github.com/ebfe/go.pcsclite? If yes why do you continue to maintain 2 repositories?
Maybe you should make that clear in the README.md file.

https://github.com/ebfe/scard has _no_ README.md file so the situation is quiet complex for me :-)

**Comment by ebfe** [comment]
> What is the relation between https://github.com/ebfe/go.pcsclite 
old, libpcsclite only, likely broken.

> and https://github.com/ebfe/scard?
api changes, windows support, maybe also subtly broken by the go 1.6 cgo
changes.

> https://github.com/ebfe/scard replaces https://github.com/ebfe/go.pcsclite? 
> If yes why do you continue to maintain 2 repositories?
Neither is really maintained, the last commit on this repo was 2 years
ago. I wanted to make incompatible API changes and there were some uses
if ebfe/go.pcsclite i did not want to update/break. Thus github.com/ebfe/scard.

> https://github.com/ebfe/scard has _no_ README.md file
That's on purpose.

> so the situation is quiet complex for me :-)
If you want to use PCSC from Go I suggest github.com/ebfe/scard. Expect
bugs. I'm sure you know the PCSC API ;) and most things map 1:1.

Here's a godoc link https://godoc.org/github.com/ebfe/scard.

**Comment by LudovicRousseau** [comment]
Hello, I wrote an article about your wrapper in http://ludovicrousseau.blogspot.fr/2016/09/pcsc-sample-in-go.html

**Comment by ebfe** [comment]
Well, the whole purpose of not having README/documentation was discouraging people from using it... but thanks i guess. The reason I didn't want to advertise is that there might still be (subtle and not so subtle) memory layout/gc issues.

**Comment by LudovicRousseau** [comment]
The main force of free software is that you can publish _unfinished_ code and hope for help from your users.
A lot of bugs in my free software programs have been found (and sometimes fixed) by users.

**Comment by ebfe** [comment]
That's the best case scenario, I'm not that optimistic :). Anyways i've added a
README to ebfe/scard and marked ebfe/go.pcsclite as deprecated. If you have
suggestions on how to improve it further...

I'm somewhat reluctant to add API docs to individual functions/constants since
this documentation already exists in several places (apart from time
constraints).
